2020-03-27 21:24:55,739 - instabot version: 0.116.0 (bot) - INFO - Instabot version: 0.116.0 Started
2020-03-27 21:24:55,739 - instabot version: 0.116.0 (bot) - DEBUG - Bot imported from /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/instabot/bot/bot.py
2020-03-27 21:25:24,325 - instabot version: 0.116.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2020-03-27 21:25:25,442 - instabot version: 0.116.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [200]>
2020-03-27 21:25:26,248 - instabot version: 0.116.0 (api) - DEBUG - POST to endpoint: qe/sync/ returned response: <Response [200]>
2020-03-27 21:25:27,534 - instabot version: 0.116.0 (api) - DEBUG - POST to endpoint: launcher/sync/ returned response: <Response [200]>
2020-03-27 21:25:28,152 - instabot version: 0.116.0 (api) - DEBUG - POST to endpoint: accounts/contact_point_prefill/ returned response: <Response [200]>
2020-03-27 21:25:29,127 - instabot version: 0.116.0 (api) - DEBUG - POST to endpoint: accounts/login/ returned response: <Response [400]>
2020-03-27 21:25:29,128 - instabot version: 0.116.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message": "The username you entered doesn\'t appear to belong to an account. Please check your username and try again.", "invalid_credentials": true, "error_title": "Incorrect Username", "buttons": [{"title": "Try Again", "action": "dismiss"}], "status": "fail", "error_type": "invalid_user"}'
2020-03-27 21:25:29,128 - instabot version: 0.116.0 (api) - ERROR - Request returns 400 error!
2020-03-27 21:25:29,128 - instabot version: 0.116.0 (api) - INFO - Instagram's error message: The username you entered doesn't appear to belong to an account. Please check your username and try again.
2020-03-27 21:25:29,128 - instabot version: 0.116.0 (api) - INFO - Error type: invalid_user
2020-03-27 21:25:29,128 - instabot version: 0.116.0 (api) - ERROR - Failed to login go to instagram and change your password
2020-03-27 21:25:29,128 - instabot version: 0.116.0 (api) - INFO - Username or password is incorrect.
2020-03-27 21:28:42,789 - instabot version: 0.116.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2020-03-27 21:28:43,808 - instabot version: 0.116.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [200]>
2020-03-27 21:28:44,675 - instabot version: 0.116.0 (api) - DEBUG - POST to endpoint: qe/sync/ returned response: <Response [200]>
2020-03-27 21:28:45,727 - instabot version: 0.116.0 (api) - DEBUG - POST to endpoint: launcher/sync/ returned response: <Response [200]>
2020-03-27 21:28:46,778 - instabot version: 0.116.0 (api) - DEBUG - POST to endpoint: accounts/contact_point_prefill/ returned response: <Response [200]>
2020-03-27 21:28:47,821 - instabot version: 0.116.0 (api) - DEBUG - POST to endpoint: accounts/login/ returned response: <Response [400]>
2020-03-27 21:28:47,821 - instabot version: 0.116.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message": "The username you entered doesn\'t appear to belong to an account. Please check your username and try again.", "invalid_credentials": true, "error_title": "Incorrect Username", "buttons": [{"title": "Try Again", "action": "dismiss"}], "status": "fail", "error_type": "invalid_user"}'
2020-03-27 21:28:47,822 - instabot version: 0.116.0 (api) - ERROR - Request returns 400 error!
2020-03-27 21:28:47,822 - instabot version: 0.116.0 (api) - INFO - Instagram's error message: The username you entered doesn't appear to belong to an account. Please check your username and try again.
2020-03-27 21:28:47,822 - instabot version: 0.116.0 (api) - INFO - Error type: invalid_user
2020-03-27 21:28:47,822 - instabot version: 0.116.0 (api) - ERROR - Failed to login go to instagram and change your password
2020-03-27 21:28:47,822 - instabot version: 0.116.0 (api) - INFO - Username or password is incorrect.
2020-03-27 21:29:38,928 - instabot version: 0.116.0 (api_login) - DEBUG - Loading cookies
2020-03-27 21:29:38,928 - instabot version: 0.116.0 (api_login) - DEBUG - Loading uuids
2020-03-27 21:29:38,929 - instabot version: 0.116.0 (api_login) - INFO - Recovery from /Users/Darshini/Downloads/social_media_posting/config/faaaanTESTic_uuid_and_cookie.json: COOKIE True - UUIDs True - TIMING, DEVICE and ...
- user-agent=Instagram 117.0.0.28.123 Android (28/9.0; 420dpi; 1080x1920; OnePlus; ONEPLUS A3003; OnePlus3; qcom; en_US; 180322800)
- phone_id=25583937-87c6-4857-828f-0ba8320d3639
- uuid=d93a6e36-ac5e-4c7d-b154-2f2820f22406
- client_session_id=84fb31dd-67b2-4a93-8602-5c5d345f9638
- device_id=android-8e51abc100ef0e36
2020-03-27 21:29:38,929 - instabot version: 0.116.0 (api_login) - INFO - LOGIN FLOW! Just logged-in: False
2020-03-27 21:29:40,332 - instabot version: 0.116.0 (api) - DEBUG - POST to endpoint: feed/timeline/ returned response: <Response [200]>
2020-03-27 21:29:41,303 - instabot version: 0.116.0 (api) - DEBUG - POST to endpoint: feed/reels_tray/ returned response: <Response [200]>
2020-03-27 21:29:41,312 - instabot version: 0.116.0 (api) - INFO - Logged-in successfully as 'faaaanTESTic'!
2020-03-27 21:29:41,313 - instabot version: 0.116.0 (bot_checkpoint) - DEBUG - Loading Checkpoint file from: /Users/Darshini/Downloads/social_media_posting/config/faaaanTESTic.checkpoint
2020-03-27 21:29:50,168 - instabot version: 0.116.0 (bot_checkpoint) - DEBUG - Saving Checkpoint file to: /Users/Darshini/Downloads/social_media_posting/config/faaaanTESTic.checkpoint
2020-03-27 21:29:50,178 - instabot version: 0.116.0 (bot) - INFO - Total requests: 31
